### ISSUE TITLE
Sözlerni Bashqa belgiler bilen ipadileshning zörüriyiti barmu?

### ISSUE THREAD

**Issue by gheyret** [ishirkhan/u-open-imla#1]
Sozluk ambirini kordum. echip korse, hemmisi bashqa bir xil shekilge ozgertilgen iken. mushundaq qilishning zoruryiti barmu?

**Comment by SilvaQ** [comment]
因有些特殊情况的考虑所有内容转码保存，使用时都使用了转么后的内容了。
这样处理有以下几个初衷：
1. 由于不知道什么是特殊敏感词，也没找到敏感词列表，而很多时候搜索程序都只考虑维吾尔语编码范围内的内容来确定目标，转码一定程度避免了直接锁定的风险
2. 字符占用空间角度 一个维吾尔语字符和同等acii码字符占用空间大小不同，理论上可以节省1/3的大小
3. 有些场景就因为字符集问题导致出现意想不到的情况，转码后全部acii嘛，对整个结果来说几乎不存在字符集风险。虽然utf-8通用，但是网络传输内容转码传输中就算被拦截也不会被列入黑名单
4. 还有其他考虑所在，所以所有本地和网盘数据都是转码存放的。

每个人的安全意识不同，一旦存在什么风险很多人有可能因素受影响，所以也希望所有跟这个项目相关的内容都进行转码处理。
当然了我们在项目中明确提供了加密解密算法，按需转换成自己需要的方式进行处理即可
具体转码，解码程序在这里：
[加密-解密程序在此](https://github.com/ishirkhan/u-open-imla/blob/main/code/python/shirkhan/src/shirkhan/encode_decode.py)
