### ISSUE TITLE
Hazirqi Zaman Uyghur Edebiy Tilining Imla Lughiti

### ISSUE THREAD

**Issue by gheyret** [ishirkhan/u-open-imla#2]
Hazirqi Zaman Uyghur Edebiy Tilining Imla Lughiti(2009) ni qoshup qoysingiz bolghudek.

**Comment by SilvaQ** [comment]
好的，可以的。书直接放在项目中不太合适，因为我们没有授权过不能传播。我找找有没有其他人共享的资源链接。

**Comment by gheyret** [comment]
https://drive.google.com/file/d/1ozsY5o6BpH8F_uUHz0rDi6pCHO5Gy9yA/view?usp=sharing
